### PR TITLE
Use 11ty static site generator

### PR DESCRIPTION
**Pull request by rjbeers**
[11ty](https://www.11ty.dev/) is "a simpler static site generator". For our purposes, it allows for templating the HTML using nunjucks or a few other options. It results in independent pages, unlike Gatsby or Nextjs's SPA output. This makes porting the use of global css and jquery easy.

TODOs: 
- [x] [choose a template language](https://www.11ty.dev/docs/languages/)
- [x] Address #34 in some form to show the usefulness of 11ty
- [x] Update netlify settings:
  - Run `npm build` before publishing
  - Publish the `_site` folder instead of the root directory

### CODE REVIEW

**Comment by rjbeers** [comment]
I hope `package-lock.json linguist-generated=true` takes effect after it is merged. I have always struggled to get this to work on the enterprise version of github.

**Comment by rjbeers** [comment]
@xanderyzwich have time to review?

**Comment by xanderyzwich** [comment]
I'm not seeing any template usage. City pages were converted directly to njk. It would seem more helpful to me to make city specific md files and a single template njk.

**Comment by rjbeers** [comment]
In order to move to inheritance style templates with markdown content inside, we'd need to accomplish two things.

1. Unify page layouts to a single template with one dynamic content block (or create many layouts, but ideally the layouts are reused some to save us from duplicating code)
2. Accomplish content definition with pure markdown (so remove any extra formatting, images, or styles unable in markdown syntax)

The first one is possible with some agreed upon site theming. I've taken a step toward this in this PR by fixing inconsistencies in header/footer between pages. We need to agree on what the layout of city pages should be and likley craft a new layout for those pages or unify it with the existing layout. primary and secondary CSS are small and nearly identical. One could resolve the two into one without too much trouble.

Overall, I think we are moving in the right direction with this pull request and can continue discussing where to go from here after we release this.

**Pull request merged**
